name: rs
description: A simple Revolt bot that interacts with the revolt.social API. Built using Volt library.
publish_to: none

environment:
    sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
    lints:

dependencies:
    http: ^0.13.3
    volt:
        git: https://github.com/volt-framework/volt.git
